CREATE TABLE SUPPLIERS
(
  SUP_ID   INTEGER     NOT NULL,
  SUP_NAME VARCHAR(40) NOT NULL,
  STREET   VARCHAR(40) NOT NULL,
  CITY     VARCHAR(20) NOT NULL,
  STATE    CHAR(2)     NOT NULL,
  ZIP      CHAR(5),
  PRIMARY KEY (SUP_ID)
);

CREATE TABLE COFFEES
(
  COF_NAME VARCHAR(32)    NOT NULL,
  SUP_ID   INT            NOT NULL,
  PRICE    NUMERIC(10, 2) NOT NULL,
  SALES    INTEGER        NOT NULL,
  TOTAL    INTEGER        NOT NULL,
  PRIMARY KEY (COF_NAME),
  FOREIGN KEY (SUP_ID) REFERENCES SUPPLIERS (SUP_ID)
);

CREATE TABLE COFFEE_DESCRIPTIONS
(
  COF_NAME VARCHAR(32) NOT NULL,
  COF_DESC BLOB        NOT NULL,
  PRIMARY KEY (COF_NAME),
  FOREIGN KEY (COF_NAME) REFERENCES COFFEES (COF_NAME)
);

CREATE TABLE RSS_FEEDS
(
  RSS_NAME     VARCHAR(32) NOT NULL,
  RSS_FEED_XML LONGTEXT    NOT NULL,
  PRIMARY KEY (RSS_NAME)
);

CREATE TABLE COF_INVENTORY
(
  WAREHOUSE_ID INTEGER     NOT NULL,
  COF_NAME     VARCHAR(32) NOT NULL,
  SUP_ID       INT         NOT NULL,
  QUAN         INT         NOT NULL,
  DATE_VAL     TIMESTAMP,
  FOREIGN KEY (COF_NAME) REFERENCES COFFEES (COF_NAME),
  FOREIGN KEY (SUP_ID) REFERENCES SUPPLIERS (SUP_ID)
);

CREATE TABLE MERCH_INVENTORY
(
  ITEM_ID   INTEGER NOT NULL,
  ITEM_NAME VARCHAR(20),
  SUP_ID    INT,
  QUAN      INT,
  DATE_VAL  TIMESTAMP,
  PRIMARY KEY (ITEM_ID),
  FOREIGN KEY (SUP_ID) REFERENCES SUPPLIERS (SUP_ID)
);

CREATE TABLE COFFEE_HOUSES
(
  STORE_ID INTEGER NOT NULL,
  CITY     VARCHAR(32),
  COFFEE   INT     NOT NULL,
  MERCH    INT     NOT NULL,
  TOTAL    INT     NOT NULL,
  PRIMARY KEY (STORE_ID)
);

CREATE TABLE DATA_REPOSITORY
(
  DOCUMENT_NAME VARCHAR(50),
  URL           VARCHAR(200)
);